# Site settings
title: José Magalhães - Portfolio
description: My portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: José Magalhães (they/them)
user_description: A passionate developer from Fortaleza, Brazil
user_title: Software Developer
email: zehra.dmg@icloud.com
github_username:  zehra-days

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
