# Site settings
title: José Magalhães Portfolio
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: José Magalhães
user_description: A passionate front-end developer from Fortaleza, Brazil
user_title: Software Developer
email: zneto@live.com
github_username:  zehra-days

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
